# Generated by Django 4.0.4 on 2022-05-02 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='documents', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpeg', 'jpg', 'tiff'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(choices=[('adh', 'Aadhar'), ('pan', 'Pan Card')], max_length=4)),
            ],
        ),
    ]
