# Generated by Django 4.0.4 on 2022-05-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
