# Generated by Django 4.0.4 on 2022-04-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ocr.document')),
            ],
        ),
    ]
