AZKEY1 = "e4054d5dbc0042e3b9ae8ffdf3cb7459"
AZKEY2 = "281b5f1d195040789e18b1ef3d824074"
ENDPOINT = "https://aman-shitta.cognitiveservices.azure.com/"

def rearrange_output(data):
      words = []
      try:
         for line in data['lines']:
               for word in line['words']:
                  # cords = [int(i) for i in word['bounding_box'].split(',')]
                  cords = (word['bounding_box'][0], word['bounding_box'][1], word['bounding_box'][-4],word['bounding_box'][-3])
                  WORD = word['text']
                  conf = word["confidence"]*100
                  words.append(((cords, WORD, conf)))
      except Exception as e:
         print(f"reaggrange_output :: Exception :: {str(e)}")
      
      return words

DATA = {
   "page":1,
   "angle":0.0855,
   "width":515.0,
   "height":680.0,
   "unit":"pixel",
   "lines":[
      {
         "bounding_box":[
            24.0,
            5.0,
            442.0,
            3.0,
            442.0,
            33.0,
            24.0,
            36.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"Have you ever seen code so",
         "words":[
            {
               "bounding_box":[
                  24.0,
                  5.0,
                  100.0,
                  6.0,
                  100.0,
                  36.0,
                  24.0,
                  36.0
               ],
               "text":"Have",
               "confidence":0.993
            },
            {
               "bounding_box":[
                  106.0,
                  6.0,
                  159.0,
                  6.0,
                  159.0,
                  36.0,
                  106.0,
                  36.0
               ],
               "text":"you",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  171.0,
                  6.0,
                  238.0,
                  6.0,
                  238.0,
                  35.0,
                  171.0,
                  36.0
               ],
               "text":"ever",
               "confidence":0.989
            },
            {
               "bounding_box":[
                  244.0,
                  6.0,
                  311.0,
                  6.0,
                  310.0,
                  34.0,
                  244.0,
                  35.0
               ],
               "text":"seen",
               "confidence":0.989
            },
            {
               "bounding_box":[
                  323.0,
                  6.0,
                  396.0,
                  5.0,
                  395.0,
                  33.0,
                  322.0,
                  34.0
               ],
               "text":"code",
               "confidence":0.989
            },
            {
               "bounding_box":[
                  401.0,
                  4.0,
                  435.0,
                  4.0,
                  435.0,
                  32.0,
                  401.0,
                  33.0
               ],
               "text":"so",
               "confidence":0.998
            }
         ]
      },
      {
         "bounding_box":[
            24.0,
            42.0,
            383.0,
            43.0,
            383.0,
            77.0,
            24.0,
            74.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"bad it made you laugh?",
         "words":[
            {
               "bounding_box":[
                  25.0,
                  43.0,
                  79.0,
                  43.0,
                  79.0,
                  74.0,
                  25.0,
                  72.0
               ],
               "text":"bad",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  86.0,
                  43.0,
                  109.0,
                  43.0,
                  109.0,
                  75.0,
                  86.0,
                  74.0
               ],
               "text":"it",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  115.0,
                  43.0,
                  202.0,
                  43.0,
                  202.0,
                  76.0,
                  115.0,
                  75.0
               ],
               "text":"made",
               "confidence":0.991
            },
            {
               "bounding_box":[
                  208.0,
                  43.0,
                  265.0,
                  44.0,
                  264.0,
                  77.0,
                  208.0,
                  76.0
               ],
               "text":"you",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  274.0,
                  44.0,
                  382.0,
                  44.0,
                  382.0,
                  77.0,
                  273.0,
                  77.0
               ],
               "text":"laugh?",
               "confidence":0.997
            }
         ]
      },
      {
         "bounding_box":[
            91.0,
            111.0,
            426.0,
            111.0,
            426.0,
            135.0,
            91.0,
            134.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"David Seidman, former Security",
         "words":[
            {
               "bounding_box":[
                  91.0,
                  113.0,
                  151.0,
                  112.0,
                  151.0,
                  134.0,
                  91.0,
                  133.0
               ],
               "text":"David",
               "confidence":0.994
            },
            {
               "bounding_box":[
                  155.0,
                  112.0,
                  256.0,
                  112.0,
                  256.0,
                  135.0,
                  155.0,
                  134.0
               ],
               "text":"Seidman,",
               "confidence":0.996
            },
            {
               "bounding_box":[
                  260.0,
                  112.0,
                  332.0,
                  112.0,
                  332.0,
                  135.0,
                  260.0,
                  135.0
               ],
               "text":"former",
               "confidence":0.997
            },
            {
               "bounding_box":[
                  337.0,
                  112.0,
                  425.0,
                  112.0,
                  425.0,
                  136.0,
                  337.0,
                  135.0
               ],
               "text":"Security",
               "confidence":0.996
            }
         ]
      },
      {
         "bounding_box":[
            91.0,
            141.0,
            412.0,
            139.0,
            412.0,
            164.0,
            91.0,
            165.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"Program Manager at Microsoft",
         "words":[
            {
               "bounding_box":[
                  92.0,
                  142.0,
                  173.0,
                  141.0,
                  173.0,
                  165.0,
                  92.0,
                  165.0
               ],
               "text":"Program",
               "confidence":0.997
            },
            {
               "bounding_box":[
                  184.0,
                  141.0,
                  277.0,
                  141.0,
                  277.0,
                  165.0,
                  184.0,
                  165.0
               ],
               "text":"Manager",
               "confidence":0.997
            },
            {
               "bounding_box":[
                  282.0,
                  141.0,
                  302.0,
                  141.0,
                  302.0,
                  165.0,
                  282.0,
                  165.0
               ],
               "text":"at",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  307.0,
                  141.0,
                  412.0,
                  140.0,
                  413.0,
                  164.0,
                  307.0,
                  165.0
               ],
               "text":"Microsoft",
               "confidence":0.995
            }
         ]
      },
      {
         "bounding_box":[
            93.0,
            168.0,
            214.0,
            169.0,
            214.0,
            191.0,
            93.0,
            190.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"(2005-2016)",
         "words":[
            {
               "bounding_box":[
                  94.0,
                  168.0,
                  214.0,
                  170.0,
                  214.0,
                  191.0,
                  94.0,
                  191.0
               ],
               "text":"(2005-2016)",
               "confidence":0.991
            }
         ]
      },
      {
         "bounding_box":[
            92.0,
            203.0,
            392.0,
            203.0,
            392.0,
            223.0,
            92.0,
            223.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"Answered Feb 8 · Upvoted by Aveesha",
         "words":[
            {
               "bounding_box":[
                  93.0,
                  204.0,
                  169.0,
                  204.0,
                  168.0,
                  223.0,
                  92.0,
                  222.0
               ],
               "text":"Answered",
               "confidence":0.994
            },
            {
               "bounding_box":[
                  173.0,
                  204.0,
                  203.0,
                  203.0,
                  202.0,
                  223.0,
                  172.0,
                  223.0
               ],
               "text":"Feb",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  207.0,
                  203.0,
                  217.0,
                  203.0,
                  216.0,
                  223.0,
                  206.0,
                  223.0
               ],
               "text":"8",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  221.0,
                  203.0,
                  226.0,
                  203.0,
                  226.0,
                  224.0,
                  220.0,
                  224.0
               ],
               "text":"·",
               "confidence":0.599
            },
            {
               "bounding_box":[
                  230.0,
                  203.0,
                  296.0,
                  203.0,
                  296.0,
                  224.0,
                  229.0,
                  224.0
               ],
               "text":"Upvoted",
               "confidence":0.996
            },
            {
               "bounding_box":[
                  300.0,
                  203.0,
                  319.0,
                  204.0,
                  319.0,
                  224.0,
                  299.0,
                  224.0
               ],
               "text":"by",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  323.0,
                  204.0,
                  392.0,
                  204.0,
                  392.0,
                  224.0,
                  323.0,
                  224.0
               ],
               "text":"Aveesha",
               "confidence":0.997
            }
         ]
      },
      {
         "bounding_box":[
            91.0,
            228.0,
            391.0,
            228.0,
            391.0,
            247.0,
            91.0,
            247.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"Sharma, Masters of Science Software",
         "words":[
            {
               "bounding_box":[
                  92.0,
                  229.0,
                  156.0,
                  229.0,
                  156.0,
                  248.0,
                  92.0,
                  248.0
               ],
               "text":"Sharma,",
               "confidence":0.995
            },
            {
               "bounding_box":[
                  160.0,
                  229.0,
                  225.0,
                  229.0,
                  225.0,
                  248.0,
                  159.0,
                  248.0
               ],
               "text":"Masters",
               "confidence":0.997
            },
            {
               "bounding_box":[
                  229.0,
                  229.0,
                  246.0,
                  229.0,
                  245.0,
                  248.0,
                  229.0,
                  248.0
               ],
               "text":"of",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  249.0,
                  229.0,
                  312.0,
                  229.0,
                  312.0,
                  248.0,
                  249.0,
                  248.0
               ],
               "text":"Science",
               "confidence":0.997
            },
            {
               "bounding_box":[
                  316.0,
                  229.0,
                  389.0,
                  229.0,
                  389.0,
                  248.0,
                  316.0,
                  248.0
               ],
               "text":"Software",
               "confidence":0.996
            }
         ]
      },
      {
         "bounding_box":[
            92.0,
            253.0,
            385.0,
            253.0,
            385.0,
            272.0,
            92.0,
            273.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"Engineering, Arizona State Univ ... and",
         "words":[
            {
               "bounding_box":[
                  93.0,
                  254.0,
                  188.0,
                  254.0,
                  188.0,
                  274.0,
                  93.0,
                  274.0
               ],
               "text":"Engineering,",
               "confidence":0.991
            },
            {
               "bounding_box":[
                  192.0,
                  254.0,
                  253.0,
                  253.0,
                  252.0,
                  273.0,
                  192.0,
                  274.0
               ],
               "text":"Arizona",
               "confidence":0.996
            },
            {
               "bounding_box":[
                  256.0,
                  253.0,
                  298.0,
                  253.0,
                  298.0,
                  273.0,
                  256.0,
                  273.0
               ],
               "text":"State",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  302.0,
                  253.0,
                  334.0,
                  253.0,
                  334.0,
                  273.0,
                  301.0,
                  273.0
               ],
               "text":"Univ",
               "confidence":0.989
            },
            {
               "bounding_box":[
                  338.0,
                  253.0,
                  349.0,
                  253.0,
                  349.0,
                  272.0,
                  337.0,
                  273.0
               ],
               "text":"...",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  353.0,
                  253.0,
                  384.0,
                  253.0,
                  384.0,
                  272.0,
                  353.0,
                  272.0
               ],
               "text":"and",
               "confidence":0.998
            }
         ]
      },
      {
         "bounding_box":[
            91.0,
            277.0,
            421.0,
            278.0,
            421.0,
            298.0,
            91.0,
            297.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"Mandeep Kaur, MS Software Engineering,",
         "words":[
            {
               "bounding_box":[
                  92.0,
                  277.0,
                  165.0,
                  277.0,
                  164.0,
                  298.0,
                  92.0,
                  298.0
               ],
               "text":"Mandeep",
               "confidence":0.994
            },
            {
               "bounding_box":[
                  169.0,
                  277.0,
                  209.0,
                  278.0,
                  208.0,
                  298.0,
                  168.0,
                  298.0
               ],
               "text":"Kaur,",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  213.0,
                  278.0,
                  240.0,
                  278.0,
                  239.0,
                  298.0,
                  213.0,
                  298.0
               ],
               "text":"MS",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  244.0,
                  278.0,
                  316.0,
                  278.0,
                  315.0,
                  299.0,
                  243.0,
                  298.0
               ],
               "text":"Software",
               "confidence":0.996
            },
            {
               "bounding_box":[
                  320.0,
                  278.0,
                  421.0,
                  279.0,
                  420.0,
                  299.0,
                  319.0,
                  299.0
               ],
               "text":"Engineering,",
               "confidence":0.991
            }
         ]
      },
      {
         "bounding_box":[
            91.0,
            302.0,
            349.0,
            302.0,
            349.0,
            322.0,
            91.0,
            321.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"San Jose State University (2017)",
         "words":[
            {
               "bounding_box":[
                  91.0,
                  303.0,
                  121.0,
                  303.0,
                  121.0,
                  321.0,
                  91.0,
                  321.0
               ],
               "text":"San",
               "confidence":0.994
            },
            {
               "bounding_box":[
                  125.0,
                  303.0,
                  164.0,
                  303.0,
                  163.0,
                  322.0,
                  125.0,
                  321.0
               ],
               "text":"Jose",
               "confidence":0.99
            },
            {
               "bounding_box":[
                  167.0,
                  303.0,
                  209.0,
                  303.0,
                  209.0,
                  322.0,
                  167.0,
                  322.0
               ],
               "text":"State",
               "confidence":0.997
            },
            {
               "bounding_box":[
                  213.0,
                  303.0,
                  292.0,
                  303.0,
                  292.0,
                  323.0,
                  213.0,
                  322.0
               ],
               "text":"University",
               "confidence":0.995
            },
            {
               "bounding_box":[
                  296.0,
                  303.0,
                  350.0,
                  303.0,
                  349.0,
                  323.0,
                  296.0,
                  323.0
               ],
               "text":"(2017)",
               "confidence":0.996
            }
         ]
      },
      {
         "bounding_box":[
            22.0,
            348.0,
            413.0,
            350.0,
            413.0,
            374.0,
            22.0,
            373.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"I was working for Microsoft's security",
         "words":[
            {
               "bounding_box":[
                  22.0,
                  349.0,
                  30.0,
                  349.0,
                  30.0,
                  374.0,
                  22.0,
                  373.0
               ],
               "text":"I",
               "confidence":0.994
            },
            {
               "bounding_box":[
                  35.0,
                  349.0,
                  74.0,
                  349.0,
                  74.0,
                  374.0,
                  35.0,
                  374.0
               ],
               "text":"was",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  79.0,
                  349.0,
                  164.0,
                  349.0,
                  164.0,
                  375.0,
                  79.0,
                  374.0
               ],
               "text":"working",
               "confidence":0.997
            },
            {
               "bounding_box":[
                  169.0,
                  349.0,
                  198.0,
                  350.0,
                  198.0,
                  375.0,
                  169.0,
                  375.0
               ],
               "text":"for",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  203.0,
                  350.0,
                  319.0,
                  350.0,
                  319.0,
                  375.0,
                  203.0,
                  375.0
               ],
               "text":"Microsoft's",
               "confidence":0.994
            },
            {
               "bounding_box":[
                  324.0,
                  350.0,
                  412.0,
                  350.0,
                  411.0,
                  375.0,
                  324.0,
                  375.0
               ],
               "text":"security",
               "confidence":0.996
            }
         ]
      },
      {
         "bounding_box":[
            23.0,
            381.0,
            428.0,
            382.0,
            428.0,
            408.0,
            23.0,
            406.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"incident response team investigating a",
         "words":[
            {
               "bounding_box":[
                  24.0,
                  382.0,
                  110.0,
                  383.0,
                  109.0,
                  407.0,
                  23.0,
                  405.0
               ],
               "text":"incident",
               "confidence":0.996
            },
            {
               "bounding_box":[
                  114.0,
                  383.0,
                  208.0,
                  384.0,
                  208.0,
                  408.0,
                  114.0,
                  407.0
               ],
               "text":"response",
               "confidence":0.996
            },
            {
               "bounding_box":[
                  213.0,
                  384.0,
                  260.0,
                  384.0,
                  260.0,
                  408.0,
                  212.0,
                  408.0
               ],
               "text":"team",
               "confidence":0.991
            },
            {
               "bounding_box":[
                  272.0,
                  384.0,
                  409.0,
                  383.0,
                  408.0,
                  408.0,
                  271.0,
                  408.0
               ],
               "text":"investigating",
               "confidence":0.993
            },
            {
               "bounding_box":[
                  414.0,
                  383.0,
                  428.0,
                  383.0,
                  427.0,
                  408.0,
                  413.0,
                  408.0
               ],
               "text":"a",
               "confidence":0.998
            }
         ]
      },
      {
         "bounding_box":[
            22.0,
            414.0,
            491.0,
            414.0,
            491.0,
            440.0,
            22.0,
            442.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"vulnerability. We opened up the relevant file.",
         "words":[
            {
               "bounding_box":[
                  23.0,
                  415.0,
                  163.0,
                  416.0,
                  163.0,
                  442.0,
                  22.0,
                  440.0
               ],
               "text":"vulnerability.",
               "confidence":0.993
            },
            {
               "bounding_box":[
                  168.0,
                  416.0,
                  198.0,
                  416.0,
                  198.0,
                  442.0,
                  168.0,
                  442.0
               ],
               "text":"We",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  203.0,
                  416.0,
                  282.0,
                  416.0,
                  282.0,
                  442.0,
                  203.0,
                  442.0
               ],
               "text":"opened",
               "confidence":0.997
            },
            {
               "bounding_box":[
                  287.0,
                  416.0,
                  313.0,
                  416.0,
                  313.0,
                  442.0,
                  287.0,
                  442.0
               ],
               "text":"up",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  318.0,
                  416.0,
                  352.0,
                  416.0,
                  352.0,
                  441.0,
                  318.0,
                  442.0
               ],
               "text":"the",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  357.0,
                  416.0,
                  443.0,
                  415.0,
                  444.0,
                  439.0,
                  357.0,
                  441.0
               ],
               "text":"relevant",
               "confidence":0.996
            },
            {
               "bounding_box":[
                  448.0,
                  415.0,
                  491.0,
                  414.0,
                  491.0,
                  438.0,
                  449.0,
                  439.0
               ],
               "text":"file.",
               "confidence":0.993
            }
         ]
      },
      {
         "bounding_box":[
            23.0,
            448.0,
            467.0,
            448.0,
            467.0,
            472.0,
            23.0,
            472.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"It contained 10,000 lines of uncommented",
         "words":[
            {
               "bounding_box":[
                  24.0,
                  450.0,
                  39.0,
                  450.0,
                  38.0,
                  471.0,
                  24.0,
                  470.0
               ],
               "text":"It",
               "confidence":0.995
            },
            {
               "bounding_box":[
                  43.0,
                  450.0,
                  148.0,
                  449.0,
                  148.0,
                  473.0,
                  43.0,
                  471.0
               ],
               "text":"contained",
               "confidence":0.995
            },
            {
               "bounding_box":[
                  153.0,
                  449.0,
                  222.0,
                  449.0,
                  222.0,
                  473.0,
                  153.0,
                  473.0
               ],
               "text":"10,000",
               "confidence":0.997
            },
            {
               "bounding_box":[
                  227.0,
                  449.0,
                  279.0,
                  449.0,
                  279.0,
                  473.0,
                  227.0,
                  473.0
               ],
               "text":"lines",
               "confidence":0.997
            },
            {
               "bounding_box":[
                  283.0,
                  449.0,
                  306.0,
                  449.0,
                  306.0,
                  473.0,
                  283.0,
                  473.0
               ],
               "text":"of",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  310.0,
                  449.0,
                  462.0,
                  450.0,
                  463.0,
                  470.0,
                  310.0,
                  473.0
               ],
               "text":"uncommented",
               "confidence":0.994
            }
         ]
      },
      {
         "bounding_box":[
            23.0,
            482.0,
            418.0,
            482.0,
            418.0,
            507.0,
            23.0,
            505.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"archaic C code. At the top was a single",
         "words":[
            {
               "bounding_box":[
                  24.0,
                  483.0,
                  98.0,
                  483.0,
                  97.0,
                  505.0,
                  24.0,
                  503.0
               ],
               "text":"archaic",
               "confidence":0.991
            },
            {
               "bounding_box":[
                  102.0,
                  483.0,
                  116.0,
                  483.0,
                  115.0,
                  505.0,
                  102.0,
                  505.0
               ],
               "text":"C",
               "confidence":0.996
            },
            {
               "bounding_box":[
                  122.0,
                  483.0,
                  179.0,
                  483.0,
                  179.0,
                  506.0,
                  122.0,
                  505.0
               ],
               "text":"code.",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  184.0,
                  483.0,
                  209.0,
                  483.0,
                  208.0,
                  507.0,
                  184.0,
                  506.0
               ],
               "text":"At",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  213.0,
                  483.0,
                  247.0,
                  482.0,
                  247.0,
                  507.0,
                  213.0,
                  507.0
               ],
               "text":"the",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  252.0,
                  482.0,
                  287.0,
                  482.0,
                  286.0,
                  507.0,
                  251.0,
                  507.0
               ],
               "text":"top",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  292.0,
                  482.0,
                  332.0,
                  482.0,
                  331.0,
                  507.0,
                  291.0,
                  507.0
               ],
               "text":"was",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  336.0,
                  482.0,
                  349.0,
                  482.0,
                  348.0,
                  507.0,
                  336.0,
                  507.0
               ],
               "text":"a",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  353.0,
                  482.0,
                  418.0,
                  482.0,
                  418.0,
                  507.0,
                  353.0,
                  507.0
               ],
               "text":"single",
               "confidence":0.997
            }
         ]
      },
      {
         "bounding_box":[
            23.0,
            517.0,
            132.0,
            517.0,
            132.0,
            535.0,
            23.0,
            536.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"comment:",
         "words":[
            {
               "bounding_box":[
                  24.0,
                  517.0,
                  132.0,
                  518.0,
                  132.0,
                  535.0,
                  23.0,
                  536.0
               ],
               "text":"comment:",
               "confidence":0.993
            }
         ]
      },
      {
         "bounding_box":[
            53.0,
            569.0,
            272.0,
            571.0,
            272.0,
            595.0,
            53.0,
            593.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"/ This code has bugs.",
         "words":[
            {
               "bounding_box":[
                  53.0,
                  569.0,
                  63.0,
                  570.0,
                  63.0,
                  594.0,
                  53.0,
                  594.0
               ],
               "text":"/",
               "confidence":0.637
            },
            {
               "bounding_box":[
                  67.0,
                  570.0,
                  113.0,
                  570.0,
                  113.0,
                  594.0,
                  67.0,
                  594.0
               ],
               "text":"This",
               "confidence":0.988
            },
            {
               "bounding_box":[
                  118.0,
                  570.0,
                  166.0,
                  571.0,
                  166.0,
                  594.0,
                  118.0,
                  594.0
               ],
               "text":"code",
               "confidence":0.991
            },
            {
               "bounding_box":[
                  171.0,
                  571.0,
                  209.0,
                  571.0,
                  209.0,
                  595.0,
                  171.0,
                  594.0
               ],
               "text":"has",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  214.0,
                  571.0,
                  272.0,
                  571.0,
                  272.0,
                  596.0,
                  214.0,
                  595.0
               ],
               "text":"bugs.",
               "confidence":0.997
            }
         ]
      },
      {
         "bounding_box":[
            22.0,
            624.0,
            88.0,
            623.0,
            88.0,
            647.0,
            22.0,
            647.0
         ],
         "appearance":{
            "style":{
               "name":"other",
               "confidence":0.972
            }
         },
         "text":"It did.",
         "words":[
            {
               "bounding_box":[
                  22.0,
                  623.0,
                  37.0,
                  623.0,
                  38.0,
                  647.0,
                  22.0,
                  647.0
               ],
               "text":"It",
               "confidence":0.998
            },
            {
               "bounding_box":[
                  42.0,
                  623.0,
                  87.0,
                  623.0,
                  88.0,
                  647.0,
                  42.0,
                  647.0
               ],
               "text":"did.",
               "confidence":0.993
            }
         ]
      }
   ]
}